# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'train_file': ['data/site_464_201710_30_train.csv']
'test_file': ['data/site_464_201710_30_test.csv']
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': ["models/templates/RCNN-resnet-50_5_layer_pretrained.pt",]
'output_dir': ["models/trained"]
#################### TASK ####################
'task_name': ["seedlings_first_last_test"]
'task_description': ["A quick test to see if the basic input of heights in the final step and the first step make any difference"]
# Could include optimizer hyperparams by making this nested. Maybe different config files for optimiser here?
#################### TRAINING ####################
'optimiser': ['ADAM']
'epochs': [200]
'patience': [10,50,100,200]
'valid_ratio': [0.1,0.2]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'learning_rate': [1,e-8,1e-6, 1e-5,1e-3]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1337, 42, 666, 43110, 1234]