# Is it possible to have hierarchical config files? XML? Hydra?
#################### DATA LOCATION ####################
'data_file': [{"train_file": 'data/new_460-464-466_201710_30_train_0.csv', "test_file": 'data/new_460-464-466_201710_30_test_0.csv'},
              {"train_file": 'data/new_460-464-466_201710_30_train_1.csv', "test_file": 'data/new_460-464-466_201710_30_test_1.csv'},
              {"train_file": 'data/new_460-464-466_201710_30_train_2.csv', "test_file": 'data/new_460-464-466_201710_30_test_2.csv'},
              {"train_file": 'data/new_460-464-466_201710_30_train_3.csv', "test_file": 'data/new_460-464-466_201710_30_test_3.csv'},
              {"train_file": 'data/new_460-464-466_201710_30_train_4.csv', "test_file": 'data/new_460-464-466_201710_30_test_4.csv'}]
#################### MODEL LOCATION ####################
'model_type': ["RCNN"]
'model_name': ["RCNN-resnet-50"]
'base_model_path': [ "models/templates/RCNN_basic_FALSE_TRUE_vanilla.pt",
                     "models/templates/RCNN_basic_FALSE_FALSE_vanilla.pt"]
'output_dir': ["models/trained"]
#,"models/templates/RCNN-resnet-50_5_layer_pretrained.pt"
#################### TASK ####################
'task_name': ["seedlings_new_data"]
'task_description': ["No pretraining on the new data with all lanes included"]
# Could include optimizer hyperparams by making this nested. Maybe different config files for optimiser here?
#################### TRAINING ####################
'optimiser': ['SGD']
'learning_rate': [2.0e-3]
'momentum': [0.9]
'weight_decay': [1.0e-4]
'epochs': [150]
'patience': [300]
'valid_ratio': [0.1]
'dataloader_num_workers': [5]
'train_batch_size': [5]
'eval_batch_size': [5]
'max_seq_length': [512]
'logging_steps': [2]
'seed': [1]
'num_weights_tracked': [10]
'device': ["cuda:0"]
'develop': [False]
'clip': [1]
# For the moment can choose from [0.1, 0.25, 0.5, 0.75, 1, 2, 5, "all"]
#'test_neg_ratio': [0.5]
#'train_neg_ratio': [0.5]